names = ['Mukund', 'Gaurav', 'Ankit', 'Nimit', 'Aryan', 'Vivek', 'Pranjal']
message = 'Hello, ' + names[0].title()
print(message)
message = 'Hello, ' + names[1].title()
print(message)
message = 'Hello, ' + names[2].title()
print(message)
message = 'Hello, ' + names[3].title()
print(message)
message = 'Hello, ' + names[4].title()
print(message)
message = 'Hello, ' + names[5].title()
print(message)
message = 'Hello, ' + names[6].title()
print(message)